image: "python:3.9"

stages:
  - Documentation

# GitLab Pages #
################
.pages:
  script:
    - pip install -U sphinx sphinx-autoapi sphinx-rtd-theme myst-parser furo
    - sphinx-build -d docs/build/doctrees docs/source docs/build/html
    - mv docs/build/html public/

test-pages:
  stage: Documentation
  tags:
    - docker
  extends: .pages
  needs: []
  artifacts:
    expose_as: 'HTML Documentation'
    paths:
      - public/
    expire_in: 1 week
  only:
    - merge_requests

pages:
  stage: Documentation
  tags:
    - pages
  extends: .pages
  artifacts:
    paths:
      - public
